version: "3"
services:
  server:
    build: .
    entrypoint: example-services server
    ports:
      - "127.0.0.1:5000:8080"
    links:
      - stock
      - jaeger
    depends_on:
      - stock
  stock:
    build: .
    entrypoint: example-services stock
    links:
      - delivery
      - jaeger
  delivery:
    build: .
    entrypoint: example-services delivery
    links:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
